require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LogsController do
before :each do
   @current_user = mock_model(User, :id => 1, :to_i=> 1, :email=>'text@test.com', :is_admin=>true, :active=>true, :accessible_folders=>Folder.scoped, :can_hotlink=>true)
   controller.stub!(:current_user).and_return(@current_user)
   controller.stub!(:login_required).and_return(:true)
  end

  fixtures :all
  render_views

  it "index should be OK" do
    get :index
  	response.should render_template(:index)
	end

  it "show should be OK" do
    get :show, :id=>Log.first.id
  	response.should render_template(:show)
	end

end
